import { DayAvailability } from './day-availability.interface';
import { Gender } from '@shared/enums/gender.enum';

export interface YMCAEvent {
    wednesday: boolean;
    tuesday: boolean;
    thursday: boolean;
    sunday: boolean;
    startTime: string;
    startDate: Date;
    saturday: boolean;
    productId: string;
    parentProduct: string;
    openSlots: number;
    numberOfClassesPerWeek: number;
    nonMemberPrice: number;
    nonmemberEarlyRegistrationPriceWithDiscount: number;
    monday: boolean;
    memberPrice: number;
    memberEarlyRegistrationPriceWithDiscount: number;
    lowGrade: string;
    lowAgeType: string;
    lowAge: number;
    locationZipCode: null;
    locationName: string;
    locationAddress: string;
    id: string;
    highGrade: string;
    highAgeType: string;
    highAge: null;
    gender: Gender;
    friday: boolean;
    endTime: string;
    endDate: Date;
    earlyRegistration: boolean;
    distance: number;
    discountPercentage: number;
    description: string;
    createdDate: Date;
    audienceApplicableTo: string;
}
